#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=4:00:00
#PBS -l vmem=31gb
#PBS -N tractseg
#PBS -V

set -x
set -e

time singularity exec -e docker://brainlife/tractseg:1.9 ./run.sh

#create tractseg output
mkdir -p output
ln -sf ../tractseg_output/bundle_segmentations output/masks

echo "Generating surfaces/ vtk from bundle_segmentations/"
time singularity exec -e docker://brainlife/pythonvtk:1.1 ./mask2surface.py

#create raw output
ln -sf tractseg_output raw

#create wmc output
mkdir -p wmc 
ln -sf ../classification.mat wmc/classification.mat
#ln -sf ../output_fibercounts.txt wmc/output_fibercounts.txt
ln -sf ../tracts wmc/tracts
ln -sf ../surfaces wmc/surfaces

#create tractmasks output
mkdir -p endingmasks
ln -sf ../tractseg_output/endings_segmentations endingmasks/masks


